automoveis = ('carros', 'motos', 'caminhoes', 'onibus', 'vans')
print(automoveis)
lista_automoveis = list(automoveis)
print('-'*30)
print(lista_automoveis)
lista_automoveis.append('aviao')
lista_automoveis.append('helicoptero')
lista_automoveis.remove('carros')
lista_automoveis.pop()
print('-'*30)
print("Primeiro da lista: " + lista_automoveis[0])
print('-'*30)
print("Ultimo da lista: " + lista_automoveis[-1])
total = len(lista_automoveis)
print('-'*30)
print("Total: " + str(total))
dicionario = {"Nome": "Clislania", "Idade": 39, "Profição":"Analista QA " }
print('-'*30)
print("Nome: " + dicionario["Nome"])